# Copyright (C) 2026 JoeyZzZzZz
# SPDX-License-Identifier: Apache-2.0
"""ConfigFile ingester: detect + ingest .conf/.cfg/.ini files from firmware.

Detection: extension-only (.conf / .cfg / .ini).
Ingestion: tolerant line parser (tracks [section] headers, accepts key=value and
key value forms, ignores # and ; comments). Classifies against CONFIG_RISK_RULES
(ordered, first-match-wins). Records ONLY flagged entries (signal-dense).
Stores the raw value in config_entries.value as evidence of firmware content,
never a generated payload. is_sensitive=1 flags hardcoded
credential candidates. Export/case-study/commit paths MUST redact sensitive values
and vendor strings.
"""

from __future__ import annotations

import re
import sqlite3

from treasure_map.lib.analyze.non_binary.framework import (
    NonBinaryFile,
    NonBinaryIngester,
)

# Ordered rule table (categorical observation labels only). Matched against the
# normalized "key=value" string; the match gates recording and drives is_sensitive,
# but the label itself is not stored. First-match-wins, compiled once at module load.
CONFIG_RISK_RULES: list[tuple[str, str]] = [
    (
        "hardcoded_credential",
        # (?<![a-zA-Z0-9]) allows _password (compound key) but blocks bypass (letter prefix)
        r"(?i)(?<![a-zA-Z0-9])(pass(word|wd)?|secret|api[_-]?key|token|priv(ate)?_?key)"
        r"(?:[_-]\w*)?\s*[=:]\s*\S",
    ),
    (
        "auth_disabled",
        # (?:[_-]\w*)? absorbs compound suffixes like _required, _enabled
        r"(?i)(?<![a-zA-Z0-9])(auth|authentication|login_required)"
        r"(?:[_-]\w*)?\s*[=:]\s*(0|no|off|false|disabled)\b",
    ),
    (
        "debug_enabled",
        r"(?i)(?<![a-zA-Z0-9])(debug|verbose|test_mode)"
        r"(?:[_-]\w*)?\s*[=:]\s*(1|yes|on|true|enabled)\b",
    ),
    (
        "weak_crypto_setting",
        r"(?i)\b(ssl|tls|cipher|crypto|hash)\b.*\b(off|none|md5|rc4|des|sslv2|sslv3|tls1\.0)\b",
    ),
]

_COMPILED_RULES: list[tuple[str, re.Pattern[str]]] = [
    (label, re.compile(pattern)) for label, pattern in CONFIG_RISK_RULES
]

_SECTION_RE = re.compile(r"^\[([^\]]+)\]")
_KV_EQ_RE = re.compile(r"^([^=\s][^=]*?)\s*=\s*(.*)")
_KV_SP_RE = re.compile(r"^(\S+)\s+(\S.*)")

_CONF_EXTENSIONS = frozenset({"conf", "cfg", "ini"})


def _detect_config(f: NonBinaryFile) -> str | None:
    """Return extension subtype if file is a config file, else None."""
    if f.text is None:
        return None
    ext = f.name.rsplit(".", 1)[-1].lower() if "." in f.name else ""
    return ext if ext in _CONF_EXTENSIONS else None


def _ingest_config(conn: sqlite3.Connection, file_id: int, f: NonBinaryFile) -> int:
    """Insert config_entries rows for security-relevant entries (flagged-only).

    key and value store the firmware's own config content as analysis evidence;
    they are never payloads generated by Treasure Map.
    """
    if f.text is None:
        return 0

    rows: list[tuple[int, str | None, str | None, str | None, int]] = []
    section: str | None = None

    for raw in f.text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(";"):
            continue

        m = _SECTION_RE.match(stripped)
        if m:
            section = m.group(1)
            continue

        key: str | None = None
        value: str | None = None

        m2 = _KV_EQ_RE.match(stripped)
        if m2:
            key = m2.group(1).strip()
            value = m2.group(2).strip()
        else:
            m3 = _KV_SP_RE.match(stripped)
            if m3:
                key = m3.group(1)
                value = m3.group(2).strip()

        if key is None:
            continue

        normalized = f"{key}={value}" if value is not None else key
        # The matched label gates recording and drives is_sensitive; it is not stored.
        matched: str | None = None
        for label, pattern in _COMPILED_RULES:
            if pattern.search(normalized):
                matched = label
                break

        if matched is None:
            continue

        is_sensitive = 1 if matched == "hardcoded_credential" else 0
        rows.append((file_id, section, key, value, is_sensitive))

    if rows:
        conn.executemany(
            """INSERT INTO config_entries
               (file_id, section, key, value, is_sensitive)
               VALUES (?, ?, ?, ?, ?)""",
            rows,
        )
    return len(rows)


CONFIG_FILE_INGESTER = NonBinaryIngester(
    kind="config_file",
    detect=_detect_config,
    ingest=_ingest_config,
)
