# Copyright (C) 2026 JoeyZzZzZz
# SPDX-License-Identifier: Apache-2.0
"""Credential ingester: detect + ingest PEM key/cert files and passwd/shadow files.

Detection priority:
  1. Basename in {passwd, shadow, master.passwd, gshadow}.
  2. Text content contains '-----BEGIN' (inline PEM).
  3. Extension in {pem, crt, cer, key, pub} (text not None).

Ingestion stores the observed artifact as verifiable evidence:
PEM blocks verbatim; passwd/shadow hash fields verbatim. material is the
firmware's OWN content — not generated by Treasure Map.
is_sensitive=1 flags private keys and present hashes for redaction on export.
Treasure Map never generates runnable attack output.
"""

from __future__ import annotations

import sqlite3

from treasure_map.lib.analyze.non_binary.framework import (
    NonBinaryFile,
    NonBinaryIngester,
)

_PASSWD_BASENAMES = frozenset({"passwd", "master.passwd"})
_SHADOW_BASENAMES = frozenset({"shadow", "gshadow"})
_PEM_EXTENSIONS = frozenset({"pem", "crt", "cer", "key", "pub"})

# Shadow $id$ prefix table → algorithm. Longer prefixes first. The algorithm name
# itself records the hash scheme (e.g. md5crypt) as structural evidence.
_SHADOW_ID_TABLE: tuple[tuple[str, str], ...] = (
    ("$2a$", "bcrypt"),
    ("$2b$", "bcrypt"),
    ("$2y$", "bcrypt"),
    ("$2$", "bcrypt"),
    ("$1$", "md5crypt"),
    ("$5$", "sha256crypt"),
    ("$6$", "sha512crypt"),
    ("$7$", "scrypt"),
    ("$y$", "yescrypt"),
)


def _detect_credential(f: NonBinaryFile) -> str | None:
    """Return subtype string if the file is a credential file, else None."""
    basename = f.name.lower()
    if basename in _PASSWD_BASENAMES:
        return "passwd"
    if basename in _SHADOW_BASENAMES:
        return "shadow"
    if f.text is not None and "-----BEGIN" in f.text:
        return "pem"
    if f.text is not None:
        ext = f.name.rsplit(".", 1)[-1].lower() if "." in f.name else ""
        if ext in _PEM_EXTENSIONS:
            return "pem"
    return None


def _extract_pem_blocks(text: str) -> list[tuple[str, str]]:
    """Return list of (type_header, full_block_text) for each BEGIN…END block."""
    blocks: list[tuple[str, str]] = []
    in_block = False
    header = ""
    block_lines: list[str] = []

    for line in text.splitlines():
        if not in_block and line.startswith("-----BEGIN ") and line.endswith("-----"):
            header = line[len("-----BEGIN ") : -len("-----")].strip()
            in_block = True
            block_lines = [line]
        elif in_block:
            block_lines.append(line)
            if line.startswith("-----END ") and line.endswith("-----"):
                blocks.append((header, "\n".join(block_lines)))
                in_block = False
                header = ""
                block_lines = []

    return blocks


def _pem_header_to_meta(header: str) -> tuple[str, str | None, int] | None:
    """Map a PEM type header to (cred_type, algorithm, is_sensitive).

    Returns None for unrecognized types (e.g. PKCS7, CSR) to stay signal-dense.
    """
    h = header.upper()
    if "PRIVATE KEY" in h:
        algo: str | None
        if "RSA" in h:
            algo = "rsa_private"
        elif "EC" in h:
            algo = "ec_private"
        elif "OPENSSH" in h:
            algo = "openssh_private"
        else:
            algo = "private"
        return ("private_key", algo, 1)
    if "CERTIFICATE" in h and "REQUEST" not in h:
        return ("certificate", None, 0)
    if "PUBLIC KEY" in h:
        return ("public_key", None, 0)
    return None


def _classify_hash(field: str) -> str:
    """Return the algorithm name for a passwd/shadow hash field."""
    for prefix, algo in _SHADOW_ID_TABLE:
        if field.startswith(prefix):
            return algo
    # 13-char legacy DES crypt (no '$')
    if len(field) == 13 and "$" not in field:
        return "des"
    return "unknown"


def _ingest_credential(conn: sqlite3.Connection, file_id: int, f: NonBinaryFile) -> int:
    """Insert credential rows for observed artifacts (evidence).

    Stores the firmware's OWN credential material — never generates attack output.
    material (PEM block / hash field) is evidence the researcher can independently
    verify. is_sensitive=1 flags private keys and present hashes for redaction before
    any export or publication.
    """
    if f.text is None:
        return 0

    subtype = _detect_credential(f)
    rows: list[tuple[int, str | None, str | None, str | None, str | None, int]] = []

    if subtype == "pem":
        for header, block in _extract_pem_blocks(f.text):
            meta = _pem_header_to_meta(header)
            if meta is None:
                continue
            cred_type, algorithm, is_sensitive = meta
            rows.append((file_id, cred_type, None, algorithm, block, is_sensitive))

    elif subtype == "passwd":
        for raw in f.text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split(":")
            if len(fields) < 4:
                continue
            identifier, pw_field = fields[0], fields[1]
            if pw_field == "":
                rows.append((file_id, "passwd_entry", identifier, None, None, 0))
            elif pw_field == "x":
                # hash in shadow; record root as informational
                if identifier == "root":
                    rows.append((file_id, "passwd_entry", identifier, None, None, 0))
            elif pw_field not in {"*", "!"}:
                algo = _classify_hash(pw_field)
                rows.append((file_id, "passwd_entry", identifier, algo, pw_field, 1))

    elif subtype == "shadow":
        for raw in f.text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split(":")
            if len(fields) < 2:
                continue
            identifier, hash_field = fields[0], fields[1]
            if hash_field == "":
                rows.append((file_id, "shadow_entry", identifier, None, None, 0))
            elif hash_field in {"*", "!", "!!"}:
                continue
            else:
                algo = _classify_hash(hash_field)
                rows.append((file_id, "shadow_entry", identifier, algo, hash_field, 1))

    if rows:
        conn.executemany(
            """INSERT INTO credentials
               (file_id, cred_type, identifier, algorithm, material, is_sensitive)
               VALUES (?, ?, ?, ?, ?, ?)""",
            rows,
        )
    return len(rows)


CREDENTIAL_INGESTER = NonBinaryIngester(
    kind="credential",
    detect=_detect_credential,
    ingest=_ingest_credential,
)
