# Copyright (C) 2025-2026 JoeyZzZzZz
# SPDX-License-Identifier: AGPL-3.0-only
"""ShellScript ingester: detect + ingest shell scripts found in firmware filesystems.

Detection: shebang line containing a known shell name, or .sh extension.
Ingestion: walk lines, classify against SHELL_RISK_RULES (ordered, first-match-wins),
record only interesting calls (signal-dense table). raw_line stores the script's
OWN source line as analysis evidence (§5.3 / D4) — it is never a generated payload.
"""

from __future__ import annotations

import re
import sqlite3

from treasure_map.lib.analyze.non_binary.framework import (
    NonBinaryFile,
    NonBinaryIngester,
)

# Ordered rule table (categorical labels only — §5.3 vocabulary).
# First-match-wins, compiled once at module load.
# Labels are CATEGORICAL. Never put a payload or runnable instruction in vuln_hint.
SHELL_RISK_RULES: list[tuple[str, str]] = [
    ("eval_injection", r"(?i)\beval\b"),
    ("cmd_injection_candidate", r"(?i)\b(sh|bash|ash|dash)\s+-c\b|`|\$\("),
    ("config_file_injection", r"(?i)\b(nvram|uci|getconf|mdb)\b"),
    ("fs_op_with_tainted", r"(?i)\b(rm|mv|cp|chmod|chown|cat|tee|dd)\b.*\$"),
]

_COMPILED_RULES: list[tuple[str, re.Pattern[str]]] = [
    (label, re.compile(pattern)) for label, pattern in SHELL_RISK_RULES
]

_KNOWN_SHELLS = frozenset({"sh", "bash", "ash", "dash", "zsh"})

# Coarse heuristic: variables that suggest the line carries user-controlled input.
_USER_INPUT_RE = re.compile(
    r"\$[1-9@*]|\$QUERY_STRING|\$REQUEST_|\$HTTP_|\$CONTENT_"
    r"|\bread\s+\w",
    re.IGNORECASE,
)


def _detect_shell(f: NonBinaryFile) -> str | None:
    """Return shell interpreter label if file is a shell script, else None."""
    if f.text is None:
        return None
    first_line = f.text.split("\n", 1)[0]
    if first_line.startswith("#!"):
        interp_field = first_line[2:].strip().split()[0] if first_line[2:].strip() else ""
        basename = interp_field.rsplit("/", 1)[-1]
        if basename in _KNOWN_SHELLS:
            return basename
    if f.name.endswith(".sh"):
        return "sh"
    return None


def _ingest_shell(conn: sqlite3.Connection, file_id: int, f: NonBinaryFile) -> int:
    """Insert script_calls rows for interesting lines in the shell script.

    Only lines that match a SHELL_RISK_RULES entry are recorded — this keeps the
    table signal-dense. raw_line stores the script's own source line as evidence;
    it is the firmware's own content, not a payload generated by Treasure Map (§5.3).
    """
    if f.text is None:
        return 0

    rows: list[tuple[int, str | None, str, int, str, int, str]] = []
    for lineno, raw in enumerate(f.text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue

        vuln_hint: str | None = None
        for label, pattern in _COMPILED_RULES:
            if pattern.search(stripped):
                vuln_hint = label
                break
        if vuln_hint is None:
            continue

        tokens = stripped.split()
        command = tokens[0] if tokens else None

        if "$" in stripped:
            args_pattern = "var_expansion"
        elif "|" in stripped:
            args_pattern = "piped"
        else:
            args_pattern = "literal"

        has_user_input = 1 if _USER_INPUT_RE.search(stripped) else 0

        rows.append((file_id, command, raw, lineno, args_pattern, has_user_input, vuln_hint))

    if rows:
        conn.executemany(
            """INSERT INTO script_calls
               (file_id, command, raw_line, line_number, args_pattern,
                has_user_input, vuln_hint)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            rows,
        )
    return len(rows)


SHELL_SCRIPT_INGESTER = NonBinaryIngester(
    kind="shell_script",
    detect=_detect_shell,
    ingest=_ingest_shell,
)
